### ISSUE TITLE
Opensource checklist

### ISSUE THREAD

**Issue by annejan** [minvws/nl-covid19-coronacheck-rivm-db-api#26]
- [x] Sanity check the code and commits
- [x] [Check license file(s) and correct if needed](https://github.com/minvws/nl-covid19-coronacheck-rivm-db-api/pull/27)
- [X] Code review by security team
- [x] Readme check
  - [x] Readability (use of domain terminology)
  - [x] Make sure you can get a working application
- [X] External code quality review
- [x] Get written approval 
  - [X] Product owner
  - [x] Management team (RDO specific: CTO)
- [x] Configure repo as public archive
- [x] Celebrate 🎉
